server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-12njfqoa.bj.tencentcdb.com:10166/Crm?useSSL=true&useUnicode=true&characterEncoding=utf8
    password: jcz3753708
    username: root